# Generated by Django 4.2 on 2024-05-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('protocol', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('organization', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'attackData',
            },
        ),
    ]
