# Generated by Django 4.2 on 2024-05-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doh_attack', '0002_attackdata_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attackData',
            new_name='attackSource',
        ),
        migrations.AlterModelTable(
            name='attacksource',
            table='attackSource',
        ),
    ]
