# Generated by Django 4.2 on 2024-05-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doh_attack', '0003_rename_attackdata_attacksource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='flowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SourceIP', models.CharField(max_length=255)),
                ('DestinationIP', models.CharField(max_length=255)),
                ('SourcePort', models.CharField(max_length=255)),
                ('DestinationPort', models.CharField(max_length=255)),
                ('TimeStamp', models.CharField(max_length=255)),
                ('Duration', models.CharField(max_length=255)),
                ('FlowBytesSent', models.CharField(max_length=255)),
                ('FlowSentRate', models.CharField(max_length=255)),
                ('FlowBytesReceived', models.CharField(max_length=255)),
                ('FlowReceivedRate', models.CharField(max_length=255)),
                ('PacketLengthVariance', models.CharField(max_length=255)),
                ('PacketLengthStandardDeviation', models.CharField(max_length=255)),
                ('PacketLengthMean', models.CharField(max_length=255)),
                ('PacketLengthMedian', models.CharField(max_length=255)),
                ('PacketLengthMode', models.CharField(max_length=255)),
                ('PacketLengthSkewFromMedian', models.CharField(max_length=255)),
                ('PacketLengthSkewFromMode', models.CharField(max_length=255)),
                ('PacketLengthCoefficientofVariation', models.CharField(max_length=255)),
                ('PacketTimeVariance', models.CharField(max_length=255)),
                ('PacketTimeStandardDeviation', models.CharField(max_length=255)),
                ('PacketTimeMean', models.CharField(max_length=255)),
                ('PacketTimeMedian', models.CharField(max_length=255)),
                ('PacketTimeMode', models.CharField(max_length=255)),
                ('PacketTimeSkewFromMedian', models.CharField(max_length=255)),
                ('PacketTimeSkewFromMode', models.CharField(max_length=255)),
                ('PacketTimeCoefficientofVariation', models.CharField(max_length=255)),
                ('ResponseTimeTimeVariance', models.CharField(max_length=255)),
                ('ResponseTimeTimeStandardDeviation', models.CharField(max_length=255)),
                ('ResponseTimeTimeMean', models.CharField(max_length=255)),
                ('ResponseTimeTimeMedian', models.CharField(max_length=255)),
                ('ResponseTimeTimeMode', models.CharField(max_length=255)),
                ('ResponseTimeTimeSkewFromMedian', models.CharField(max_length=255)),
                ('ResponseTimeTimeSkewFromMode', models.CharField(max_length=255)),
                ('ResponseTimeTimeCoefficientofVariation', models.CharField(max_length=255)),
                ('Label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'flowData',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('birth', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('useravatar', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
