# Generated by Django 4.2 on 2024-05-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doh_attack', '0004_flowdata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='shapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowID', models.IntegerField()),
                ('SourcePort_score', models.CharField(max_length=255)),
                ('Duration_score', models.CharField(max_length=255)),
                ('FlowBytesSent_score', models.CharField(max_length=255)),
                ('FlowSentRate_score', models.CharField(max_length=255)),
                ('FlowBytesReceived_score', models.CharField(max_length=255)),
                ('FlowReceivedRate_score', models.CharField(max_length=255)),
                ('PacketLengthVariance_score', models.CharField(max_length=255)),
                ('PacketLengthStandardDeviation_score', models.CharField(max_length=255)),
                ('PacketLengthMean_score', models.CharField(max_length=255)),
                ('PacketLengthMedian_score', models.CharField(max_length=255)),
                ('PacketLengthMode_score', models.CharField(max_length=255)),
                ('PacketLengthSkewFromMedian_score', models.CharField(max_length=255)),
                ('PacketLengthSkewFromMode_score', models.CharField(max_length=255)),
                ('PacketLengthCoefficientofVariation_score', models.CharField(max_length=255)),
                ('PacketTimeVariance_score', models.CharField(max_length=255)),
                ('PacketTimeStandardDeviation_score', models.CharField(max_length=255)),
                ('PacketTimeMean_score', models.CharField(max_length=255)),
                ('PacketTimeMedian_score', models.CharField(max_length=255)),
                ('PacketTimeMode_score', models.CharField(max_length=255)),
                ('PacketTimeSkewFromMedian_score', models.CharField(max_length=255)),
                ('PacketTimeSkewFromMode_score', models.CharField(max_length=255)),
                ('PacketTimeCoefficientofVariation_score', models.CharField(max_length=255)),
                ('ResponseTimeTimeVariance_score', models.CharField(max_length=255)),
                ('ResponseTimeTimeStandardDeviation_score', models.CharField(max_length=255)),
                ('ResponseTimeTimeMean_score', models.CharField(max_length=255)),
                ('ResponseTimeTimeMedian_score', models.CharField(max_length=255)),
                ('ResponseTimeTimeMode_score', models.CharField(max_length=255)),
                ('ResponseTimeTimeSkewFromMedian_score', models.CharField(max_length=255)),
                ('ResponseTimeTimeSkewFromMode_score', models.CharField(max_length=255)),
                ('ResponseTimeTimeCoefficientofVariation_score', models.CharField(max_length=255)),
                ('Label_score', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shapData',
            },
        ),
    ]
