# Generated by Django 4.2 on 2024-06-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doh_attack', '0007_flowdata_sourceportpre'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowdata',
            name='FlowBytesReceivedPre',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowdata',
            name='FlowBytesSentPre',
            field=models.CharField(default=0.1, max_length=255),
            preserve_default=False,
        ),
    ]
