# Generated by Django 4.2 on 2024-06-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doh_attack', '0008_flowdata_flowbytesreceivedpre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowdata',
            name='DurationPre',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
