# Generated by Django 4.2 on 2024-07-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doh_attack', '0009_flowdata_durationpre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('filesize', models.CharField(max_length=255)),
                ('sourceIp', models.CharField(max_length=255)),
                ('sourcePort', models.CharField(max_length=255)),
                ('destinationIp', models.CharField(max_length=255)),
                ('destinationPort', models.CharField(max_length=255)),
                ('tlsVersion', models.CharField(max_length=255)),
                ('clientCipherSuits', models.TextField(null=True)),
                ('serverAcceptedSuit', models.CharField(max_length=255)),
                ('clientExtensions', models.TextField(null=True)),
                ('serverExtensions', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('tlsSession', models.CharField(max_length=255)),
                ('packetLen', models.IntegerField()),
                ('fingerPrint', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='IP2Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipFrom', models.PositiveIntegerField()),
                ('ipTo', models.PositiveIntegerField()),
                ('countryCode', models.CharField(max_length=10)),
                ('countryName', models.CharField(max_length=255)),
                ('regionName', models.CharField(max_length=255)),
                ('cityName', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'ip2location',
            },
        ),
    ]
